application: libraryhippo27
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:
# - url: /stats.*
#   script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /admin/.*
  script: libraryhippo.application
  login: admin

- url: /.*
  script: libraryhippo.application

libraries:
- name: jinja2
  version: 2.6