"""Add Card model

Revision ID: b2fc8df2f32f
Revises: 
Create Date: 2020-02-26 06:09:16.931924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fc8df2f32f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_name', sa.String(length=64), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('pin', sa.String(length=16), nullable=True),
    sa.Column('last_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
